### ISSUE TITLE
[Request] TBTerra's spawnTracker Concept!

### ISSUE THREAD

**Issue by vinsilsim** [marbink/pogom#1]
## Checklist
 - [x] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [x] I have checked if this issue already exists (both open and closed issues)
 - [x] I am using the most recent version of pogom from the master branch
 - [x] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [x] I'm posting the complete log
 - [x] I'm using a descriptive title for this issue

## My Issue
Apply the concept of spawn search for better performance.

https://www.reddit.com/r/pokemongodev/comments/4wxteh/i_implemented_tbterras_spawntracker_into/

**Comment by marbink** [comment]
Ask directly here: https://github.com/favll/pogom
I'll implement here only some feature i need.
Good luck.
